### PR TITLE
Use acceptance testing transport

### LINKED ISSUE #185: Delaying a failed delayed message can cause message loss
I've noticed that `Recoverability.When_using_special_characters_in_headers` seems to fail quite reliably when using the acceptance testing / learning transport, mostly on .NET Core.

The observed behavior is the following:

* a message is sent with a delay
* the delayed message is delivered to the handler
* an exception in the handler causes the message to be handled by delayed retries
* the message is lost.

I've added some more logging statements to the `TimeoutPersister` class and here's the relevant part of the log:

```
18:49:36 Debug UsingSpecialCharactersInHeaders.EndpointHandlingDelayedMessages: Polling for timeouts at 19.12.2017 17:49:36.
18:49:36 Debug UsingSpecialCharactersInHeaders.EndpointHandlingDelayedMessages: GetNextChunk
18:49:36 Debug UsingSpecialCharactersInHeaders.EndpointHandlingDelayedMessages: GetNextChunk found 1 timeouts
18:49:36 Debug UsingSpecialCharactersInHeaders.EndpointHandlingDelayedMessages: Polling next retrieval is at 19.12.2017 18:49:36.
18:49:37 Debug UsingSpecialCharactersInHeaders.EndpointHandlingDelayedMessages: Peeking timeout 2db25fb3-3a52-4f32-8a85-a84e0125c281
18:49:37 Debug UsingSpecialCharactersInHeaders.EndpointHandlingDelayedMessages: Removing timeout 2db25fb3-3a52-4f32-8a85-a84e0125c281
18:49:37 Debug UsingSpecialCharactersInHeaders.EndpointHandlingDelayedMessages: Processing message 2db25fb3-3a52-4f32-8a85-a84e0125c281
18:49:37 Debug UsingSpecialCharactersInHeaders.EndpointHandlingDelayedMessages: Handle invoked
18:49:37 Warn UsingSpecialCharactersInHeaders.EndpointHandlingDelayedMessages: Delayed Retry will reschedule message '2db25fb3-3a52-4f32-8a85-a84e0125c281' after a delay of 00:00:03 because of an exception: System.Exception: require delayed retry
   at [...]
18:49:37 Debug UsingSpecialCharactersInHeaders.EndpointHandlingDelayedMessages: Completing processing for c:\temp\0-1235\UsingSpecialCharactersInHeaders.EndpointHandlingDelayedMessages\2bd2ba71-203a-4930-aca5-195ed0c4d1a1.metadata.txt(c:\temp\0-1235\UsingSpecialCharactersInHeaders.EndpointHandlingDelayedMessages\.pending\0020899b-1202-40c8-b911-2d1d73fb4dda\2bd2ba71-203a-4930-aca5-195ed0c4d1a1.metadata.txt), exception (if any): 
18:49:37 Debug UsingSpecialCharactersInHeaders.EndpointHandlingDelayedMessages: timeout 2db25fb3-3a52-4f32-8a85-a84e0125c281 already exists.
18:49:37 Debug UsingSpecialCharactersInHeaders.EndpointHandlingDelayedMessages: Completing processing for c:\temp\0-1235\UsingSpecialCharactersInHeaders.EndpointHandlingDelayedMessages-Timeouts\015911f6-0d20-44de-b24b-33acd1c63edb.metadata.txt(c:\temp\0-1235\UsingSpecialCharactersInHeaders.EndpointHandlingDelayedMessages-Timeouts\.pending\acd80028-2cdc-4450-956b-b7d8bf09205e\015911f6-0d20-44de-b24b-33acd1c63edb.metadata.txt), exception (if any): 
18:49:37 Debug UsingSpecialCharactersInHeaders.EndpointHandlingDelayedMessages: Completing processing for c:\temp\0-1235\UsingSpecialCharactersInHeaders.EndpointHandlingDelayedMessages-TimeoutsDispatcher\ea1321d7-8b27-4fae-b498-227a15f40985.metadata.txt(c:\temp\0-1235\UsingSpecialCharactersInHeaders.EndpointHandlingDelayedMessages-TimeoutsDispatcher\.pending\91f1e8c4-3028-4494-b3ae-420158435843\ea1321d7-8b27-4fae-b498-227a15f40985.metadata.txt), exception (if any): 
18:49:37 Debug UsingSpecialCharactersInHeaders.EndpointHandlingDelayedMessages: Polling for timeouts at 19.12.2017 17:49:37.
18:49:37 Debug UsingSpecialCharactersInHeaders.EndpointHandlingDelayedMessages: GetNextChunk
18:49:38 Debug UsingSpecialCharactersInHeaders.EndpointHandlingDelayedMessages: GetNextChunk found no timeouts
18:49:38 Debug UsingSpecialCharactersInHeaders.EndpointHandlingDelayedMessages: Polling next retrieval is at 19.12.2017 18:49:38.
```

when the message is delayed by delayed retries, it won't be added to the storage as it already finds a message by this ID, although that should have been deleted according to the log statements.

If the timeout persister wouldn't use the message id as the identifier for the timeout persister, this wouldn't happen. At least inmemory persistence always creates a new guid for every timeout to be stored.

ping @Particular/azure-maintainers

### PR DESCRIPTION
**Pull request by timbussmann**
Using the acceptance testing transport for the acceptance test.

Closes #185 and adds a few perf tweaks.

### CODE REVIEW

**Comment by timbussmann** [comment]
@Particular/azure-maintainers it looks like the `Recoverability.When_using_special_characters_in_headers` fails when running on .NET Core. Is that something you've noticed before?

**Comment by boblangley** [comment]
@timbussmann Not that I am aware of.

**Comment by timbussmann** [comment]
@boblangley I looked a bit into the issue and raised a bug here: https://github.com/Particular/NServiceBus.Persistence.AzureStorage/issues/185

**Comment by bording** [comment]
I believe this should be against the release branch, not develop.

File: src/AcceptanceTests/ConfigureEndpointAzureStorageQueueTransport.cs [hunk 1]
```diff
@@ -1,42 +0,0 @@
-using System.Threading.Tasks;
-using NServiceBus;
-using NServiceBus.AcceptanceTesting.Support;
-
-public class ConfigureEndpointAzureStorageQueueTransport : IConfigureEndpointTestExecution
```
Comment (danielmarbach) [inline src/AcceptanceTests/ConfigureEndpointAzureStorageQueueTransport.cs]: By removing ASQ here potential regressions in the hybrid mode would not be caught, see https://github.com/Particular/NServiceBus.AzureStorageQueues/issues/301

I'm not against these changes I'm just bringing this up for future reference.

@bording, even more, reason to push for the 7.1 changes you are advocating for?

File: src/NServiceBus.Persistence.AzureStorage/Timeout/TimeoutLogic/TimeoutPersister.cs [hunk 2]
```diff
@@ -101,9 +101,14 @@ public TimeoutPersister(string timeoutConnectionString, string timeoutDataTableN
 
             try
             {
-                await DeleteSagaEntity(timeoutId, timeoutDataTable, timeoutDataEntity).ConfigureAwait(false);
-                await DeleteTimeEntity(timeoutDataTable, timeoutDataEntity.Time.ToString(partitionKeyScope), timeoutId).ConfigureAwait(false);
-                await DeleteState(timeoutDataEntity.StateAddress).ConfigureAwait(false);
+                var deleteActions = new List<Task>(3)
```
Comment (danielmarbach) [inline src/NServiceBus.Persistence.AzureStorage/Timeout/TimeoutLogic/TimeoutPersister.cs]: @dbelcham @boblangley can you weight in here? I see no reason why the deletion can't be done concurrently since the adding is also done concurrent and the three entries are separate entries.

File: src/NServiceBus.Persistence.AzureStorage/Timeout/TimeoutLogic/TimeoutPersister.cs [hunk 3]
```diff
@@ -133,12 +133,17 @@ public TimeoutPersister(string timeoutConnectionString, string timeoutDataTableN
...
             var results = await timeoutDataTable.ExecuteQueryAsync(query, take: 1000).ConfigureAwait(false);
 
+            var deletionTasks = new List<Task>(4);
             foreach (var timeoutDataEntityBySaga in results)
             {
-                await DeleteState(timeoutDataEntityBySaga.StateAddress).ConfigureAwait(false);
-                await DeleteTimeEntity(timeoutDataTable, timeoutDataEntityBySaga.Time.ToString(partitionKeyScope), timeoutDataEntityBySaga.RowKey).ConfigureAwait(false);
-                await DeleteMainEntity(timeoutDataTable, timeoutDataEntityBySaga.RowKey, string.Empty).ConfigureAwait(false);
-                await DeleteSagaEntity(timeoutDataTable, timeoutDataEntityBySaga).ConfigureAwait(false);
+                deletionTasks.Add(DeleteState(timeoutDataEntityBySaga.StateAddress));
```
Comment (danielmarbach) [inline src/NServiceBus.Persistence.AzureStorage/Timeout/TimeoutLogic/TimeoutPersister.cs]: @boblangley @dbelcham same thoughts as in my previous comment Are you OK with these changes?

File: src/AcceptanceTests/TestSuiteConstraints.cs [hunk 4]
```diff
@@ -9,7 +9,7 @@ public partial class TestSuiteConstraints
         public bool SupportsNativePubSub { get; } = false;
         public bool SupportsNativeDeferral { get; } = false;
         public bool SupportsOutbox { get; } = false;
-        public IConfigureEndpointTestExecution CreateTransportConfiguration() => new ConfigureEndpointAzureStorageQueueTransport();
+        public IConfigureEndpointTestExecution CreateTransportConfiguration() => new ConfigureEndpointAcceptanceTestingTransport(SupportsNativePubSub, SupportsNativeDeferral);
```
Comment (yvesgoeleven) [inline src/AcceptanceTests/TestSuiteConstraints.cs]: Where can I find any info on the workings of this transport?

**Comment by yvesgoeleven** [comment]
Approved the changes, but I would like to learn more about this ATT transport, what it supports and how it works, where can I find info about it?

**Comment by timbussmann** [comment]
@yvesgoeleven it's essentially the same as the learning transport, it just has configuration options to allow disabling native delayed delivery and native pubsub. @andreasohlund is the master of the learning transport.

File: src/NServiceBus.Persistence.AzureStorage/Timeout/TimeoutLogic/TimeoutPersister.cs [hunk 5]
```diff
@@ -50,19 +50,12 @@ public TimeoutPersister(string timeoutConnectionString, string timeoutDataTableN
...
+            var identifier = Guid.NewGuid().ToString();
             timeout.Id = identifier;
 
-            var timeoutDataEntity = await GetTimeoutData(timeoutDataTable, identifier, string.Empty).ConfigureAwait(false);
-            if (timeoutDataEntity != null) return;
-
             var headers = Serialize(timeout.Headers);
 
-            var saveActions = new List<Task>
+            var saveActions = new List<Task>(3)
```
Comment (timbussmann) [inline src/NServiceBus.Persistence.AzureStorage/Timeout/TimeoutLogic/TimeoutPersister.cs]: nitpicking, but wouldn't this be easier as an array?

**Comment by yvesgoeleven** [comment]
@timbussmann @andreasohlund so it's a non transactional file based one?

File: src/NServiceBus.Persistence.AzureStorage/Timeout/TimeoutLogic/TimeoutPersister.cs (hunk 5 above)
Comment (danielmarbach) [reply src/NServiceBus.Persistence.AzureStorage/Timeout/TimeoutLogic/TimeoutPersister.cs]: Thought about that and left it because below I use similar code which clears the list. More cumbersome with arrays. I felt consistency in the same file wouldnt hurt

Comment (timbussmann) [reply src/NServiceBus.Persistence.AzureStorage/Timeout/TimeoutLogic/TimeoutPersister.cs]: yeah, definitely no blocker imo.

File: src/AcceptanceTests/ConfigureEndpointAzureStorageQueueTransport.cs (hunk 1 above)
Comment (andreasohlund) [reply src/AcceptanceTests/ConfigureEndpointAzureStorageQueueTransport.cs]: >By removing ASQ here potential regressions in the hybrid mode would not be caught, see 

Since the transport "owns" the hybrid mode would it make more sense for it to pull in ASP and run those tests there?

File: src/AcceptanceTests/TestSuiteConstraints.cs (hunk 4 above)
Comment (andreasohlund) [reply src/AcceptanceTests/TestSuiteConstraints.cs]: Its a copy and paste of the LearningTransport

https://docs.particular.net/transports/learning/?version=core_7

But I guess as they start to diverge we need to start documenting the differences?

File: src/AcceptanceTests/ConfigureEndpointAzureStorageQueueTransport.cs (hunk 1 above)
Comment (timbussmann) [reply src/AcceptanceTests/ConfigureEndpointAzureStorageQueueTransport.cs]: we could have two acceptance tests projects similar to nhibernate or sqlp to run with different configurations?

**Comment by timbussmann** [comment]
@yvesgoeleven it supports transactions but not transactionscope/dtc.

File: src/NServiceBus.Persistence.AzureStorage/Timeout/TimeoutLogic/TimeoutPersister.cs (hunk 2 above)
Comment (boblangley) [reply src/NServiceBus.Persistence.AzureStorage/Timeout/TimeoutLogic/TimeoutPersister.cs]: I don't see any harm, and the tests are passing :shipit:

File: src/NServiceBus.Persistence.AzureStorage/Timeout/TimeoutLogic/TimeoutPersister.cs (hunk 3 above)
Comment (boblangley) [reply src/NServiceBus.Persistence.AzureStorage/Timeout/TimeoutLogic/TimeoutPersister.cs]: I don't see any harm, and the tests are passing :shipit:

File: src/AcceptanceTests/ConfigureEndpointAzureStorageQueueTransport.cs (hunk 1 above)
Comment (boblangley) [reply src/AcceptanceTests/ConfigureEndpointAzureStorageQueueTransport.cs]: > Since the transport "owns" the hybrid mode would it make more sense for it to pull in ASP and run those tests there?

I agree ASQ should own those tests, I am skeptical the tests need to be against ASP.

File: src/AcceptanceTests/TestSuiteConstraints.cs (hunk 4 above)
Comment (bording) [reply src/AcceptanceTests/TestSuiteConstraints.cs]: Why is `SupportsCrossQueueTransactions` false?

**Comment by danielmarbach** [comment]
This is ready for review. Not sure though if `When_removing_timeouts_from_the_storage.TryRemove_should_work_with_concurrent_operations` is a bit flaky though... It failed once on the build server.

**Comment by SeanFeldman** [comment]
Should this be ported to `develop` as well?
/cc @bording

**Comment by bording** [comment]
@SeanFeldman This will make it back to develop once the release branch is merged back to develop.

**Comment by SeanFeldman** [comment]
In that case, the issue #185 should be closed @Particular/azure-maintainers

**Comment by SeanFeldman** [comment]
Will close as it will make back into `develop`. Thanks @bording
